# Generated by Django 4.2.5 on 2024-06-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_of_docs',
            field=models.PositiveIntegerField(default=100, verbose_name='Maximum Number of Documents'),
        ),
        migrations.AddField(
            model_name='user',
            name='num_of_sources',
            field=models.PositiveIntegerField(default=100, verbose_name='Maximum Number of sources'),
        ),
    ]
