# Generated by Django 4.2.5 on 2024-06-25 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('raw_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image_alt', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='document_images/')),
                ('url', models.URLField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('detail_mode', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='control.source')),
            ],
        ),
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150)),
                ('count_visits', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.document')),
            ],
            options={
                'verbose_name': 'Shared Link',
                'verbose_name_plural': 'Shared Links',
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('header', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('header_level', models.CharField(blank=True, choices=[('H1', 'H1'), ('H2', 'H2'), ('H3', 'H3'), ('H4', 'H4'), ('H5', 'H5'), ('H6', 'H6')], default='H1', max_length=2, null=True)),
                ('anchor_text', models.CharField(blank=True, max_length=255, null=True)),
                ('anchor_url', models.CharField(blank=True, max_length=255, null=True)),
                ('context', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('summer_note', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.document')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='control.topic'),
        ),
        migrations.CreateModel(
            name='Accessability',
            fields=[
                ('term', models.CharField(blank=True, max_length=150, null=True)),
                ('position', models.IntegerField(blank=True, default=101, null=True)),
                ('volume', models.IntegerField(blank=True, default=0, null=True)),
                ('traffic', models.IntegerField(default='0')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.document')),
            ],
        ),
    ]
