# Generated by Django 5.0.6 on 2024-07-07 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_document_topic_alter_sharedlink_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='document',
        ),
        migrations.AddField(
            model_name='passage',
            name='topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='control.topic'),
        ),
    ]
