# Generated by Django 5.0.6 on 2024-07-07 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_remove_passage_document_passage_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passages_documents', to='control.topic'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passages_topics', to='control.topic'),
        ),
    ]
