# Generated by Django 5.0.6 on 2024-07-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_passage_documents_alter_passage_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='topics',
        ),
    ]
