# Generated by Django 5.0.6 on 2024-07-07 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_remove_passage_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='documents',
        ),
        migrations.AddField(
            model_name='passage',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.document'),
        ),
    ]
